version: '3.8'

services:
  app:
    build:
      context: ./password_generator
      dockerfile: Dockerfile
    command: gunicorn password_generator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/home/password/web/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - net
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./staticfiles:/home/password/web/staticfiles/
    depends_on:
      - app
    networks:
      - net
      
volumes:
  postgres_data:

networks:
  net:
    external: true
