version: '3.8'

services:
  pass:
    build:
      context: ./password_generator
      dockerfile: Dockerfile
    command: gunicorn password_generator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles_pass:/home/password/web/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - net

networks:
  net:
    external: true
